context.modules = [
  {   name = libpipewire-module-echo-cancel
      args = {
          library.name = "aec/libspa-aec-speex"

          ## Use a single microphone channel
          audio.channels = 1

          ## Instead of creating virtual sink for audio to be removed, read a monitor of the output
          monitor.mode = true

          ## Microphone input
          capture.props = {
              ## Change this line to match your sound card source!
              target.object = "alsa_input.usb-Universal_Audio_Volt_2_25272037118218-00.Direct__Direct__source"

              ## The sample rate and quantum must be set so that they match the speex.frame_length in aec.args
              node.force-rate = 48000
              node.force-quantum = 480

              ## Don't keep the connection alive, i.e. idle and suspend the link if output not in use
              node.passive = true

              node.driver = false
              node.follow = true

              ## Pick the correct channel
              audio.position = "FL"
          }

          ## Speaker to be filtered from the microphone input
          sink.props = {
              ## Change this line to match your sound card sink!
              # Use the same sound card so that we don't introduce a clock drift
              target.object = "alsa_output.usb-Universal_Audio_Volt_2_25272037118218-00.Direct__Direct__sink"

              node.passive = true

              node.force-rate = 48000
              node.force-quantum = 480
              node.driver = true
              node.follow = false

              audio.channels = 2
              audio.position = "FL,FR"
          }

          ## Resulting AEC enabled microphone source
          source.props = {
              node.name = "ua_volt_2_ch_1"
              node.description = "Volt 2 AEC"

              node.passive = true
              node.driver = false
              node.follow = true
          }

          aec.args = {
              # Default configuration values, uncomment to change
              # speex.frame_length = 10    # ms, a length of audio chunk processed at once
              # speex.filter_length = 100  # ms, the echo tail length, should reflect room acoustics
              # speex.filter_delay = 20    # ms, the latency from the sink (speakers) to the source (microphone)

              # speex.preprocess = false
              # speex.preprocess.echo_suppress = -40   # dB, library default
              # speex.preprocess.denoise = false
              # speex.preprocess.noise_suppress = -15  # dB, library default
              # speex.preprocess.dereverb = false

              # The voice activity detection is discouraged by Speex authors (see pipewire logs)
              # speex.preprocess.voice_activity_detector = false
              # speex.preprocess.echo_suppress_active = -15  # dB, library default
          }
      }
  }
]
